// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku

#define MIRYOKU_KLUDGE_TWOHANDCOMBOS_MIDINDEX 13 16
#define MIRYOKU_KLUDGE_TWOHANDCOMBOS_MIDMIDDLE 12 17
#define MIRYOKU_KLUDGE_TWOHANDCOMBOS_LOWERPINKIE 20 29

#define MIRYOKU_KLUDGE_TWOHANDCOMBOS
