# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Test Build'
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == 'drdrew42'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["temper_left nice_view_adapter nice_view","temper_right nice_view_adapter nice_view"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y"]'
      alphas: '["qwerty"]'
